import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const results=[];await mkdir('artifacts/audit',{recursive:true});
try{const context=await browser.newContext({reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const width of [360,390,430,768,1024,1440,1920]){await page.setViewportSize({width,height:width<768?844:900});for(const route of ['/','/work','/services','/pricing','/about','/contact','/work/unix-property','/work/aluna-bake-brew','/work/villa-lontar','/visual','/missing-page']){const response=await page.goto('http://127.0.0.1:4173'+route,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);await page.locator('img').evaluateAll(es=>es.forEach(e=>e.loading='eager'));await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,overflows:[...document.querySelectorAll('main *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1&&getComputedStyle(e).position!=='absolute'&&!e.closest('[aria-hidden="true"],.overflow-hidden')}).slice(0,8).map(e=>({tag:e.tagName,cls:e.className,text:e.textContent.slice(0,60)})),h1:document.querySelectorAll('h1').length,hero:document.querySelector('.hero-details')?.getBoundingClientRect().bottom,broken:[...document.images].filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src),title:document.title}));results.push({width,route,status:response.status(),...metrics});if(width===390||width===1440||route==='/')await page.screenshot({path:`artifacts/audit/${width}-${route.replaceAll('/','_')||'home'}.png`,fullPage:true});console.log(width,route,JSON.stringify(metrics));}
}
await writeFile('artifacts/audit/results.json',JSON.stringify(results,null,2));
for(const route of ['/','/work','/services','/pricing','/about','/contact','/work/unix-property','/visual']){await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:4173'+route,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();results.push({route,a11y:a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});console.log('AXE',route,JSON.stringify(results.at(-1)));}
results.push({errors});await writeFile('artifacts/audit/results.json',JSON.stringify(results,null,2));}finally{await browser.close()}
