import { chromium, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();const report={errors:[],english:[],motion:[],performance:{}};page.on('pageerror',e=>report.errors.push(e.message));await mkdir('artifacts/final',{recursive:true});
try{
await page.addInitScript(()=>{window.auditPerformance={cls:0,lcp:0};new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput)window.auditPerformance.cls+=e.value}).observe({type:'layout-shift',buffered:true});new PerformanceObserver(list=>{window.auditPerformance.lcp=list.getEntries().at(-1).startTime}).observe({type:'largest-contentful-paint',buffered:true});});
await page.goto('http://127.0.0.1:4173/');await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(1000);report.performance=await page.evaluate(()=>({...window.auditPerformance,resources:performance.getEntriesByType('resource').map(r=>({name:r.name,transfer:r.transferSize}))}));
for(const width of [390,1440]){
 await page.setViewportSize({width,height:width===390?844:900});await page.goto('http://127.0.0.1:4173/');await page.evaluate(()=>document.fonts.ready);
 for(let y=0;y<await page.evaluate(()=>document.documentElement.scrollHeight);y+=700){await page.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),y);await page.waitForTimeout(60)}
 await page.locator('img').evaluateAll(es=>es.forEach(e=>e.loading='eager'));await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));
 const sections=page.locator('main > section');for(let i=0;i<await sections.count();i++){const section=sections.nth(i);await section.scrollIntoViewIfNeeded();await page.waitForTimeout(120);await section.screenshot({path:`artifacts/final/${width}-section-${String(i).padStart(2,'0')}.png`});}
 await page.locator('footer').screenshot({path:`artifacts/final/${width}-footer.png`});
 for(const route of ['contact','pricing','services','work/unix-property']){await page.goto('http://127.0.0.1:4173/'+route);await page.locator('img').evaluateAll(es=>es.forEach(e=>e.loading='eager'));await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));await page.screenshot({path:`artifacts/final/${width}-${route.replaceAll('/','-')}.png`,fullPage:true});}
}
await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:4173/');const steps=page.locator('.story-rail button');for(let i=0;i<5;i++){await steps.nth(i).click();await expect(steps.nth(i)).toHaveAttribute('aria-current','step');report.motion.push(await page.locator('.story-scene.is-current h3').innerText());}
await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.story-track')).toHaveAttribute('data-enhanced','false');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(700);const first=await page.locator('canvas').first().screenshot();await page.waitForTimeout(700);const second=await page.locator('canvas').first().screenshot();report.reducedMotionCanvasUnchanged=first.equals(second);
await page.evaluate(()=>localStorage.setItem('wk-lang','en'));for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['/','/work','/services','/pricing','/about','/contact','/work/unix-property','/work/aluna-bake-brew','/work/villa-lontar','/visual']){await page.goto('http://127.0.0.1:4173'+route);report.english.push({width,route,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),lang:await page.locator('html').getAttribute('lang')});}}
const slow=await browser.newContext({viewport:{width:390,height:844}});const sp=await slow.newPage();let release;const gate=new Promise(r=>release=r);await sp.route('**/assets/*.js',async route=>{await gate;await route.continue()});await sp.goto('http://127.0.0.1:4173/',{waitUntil:'commit'});await expect(sp.locator('h1')).toBeVisible();await expect(sp.locator('.hero-details')).toBeVisible();await sp.screenshot({path:'artifacts/final/390-javascript-pending.png'});report.pendingJavaScriptContentVisible=true;release();await slow.close();
await writeFile('artifacts/final/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({errors:report.errors,motion:report.motion,reducedMotionCanvasUnchanged:report.reducedMotionCanvasUnchanged,pendingJavaScriptContentVisible:report.pendingJavaScriptContentVisible,englishOverflows:report.english.filter(r=>r.overflow),performance:{cls:report.performance.cls,lcp:report.performance.lcp}}));
}finally{await browser.close()}
